import { MoneyAmount } from '@/shared/types/common';

/**
 * A selected add-on within a cart item. Binary: max quantity 1 (BR-003).
 */
export interface CartAddOnSelection {
  addonId: string;
  name: string;
  unitPrice: MoneyAmount;
}

/**
 * Client-side representation of an item intended for purchase.
 * Identity is the deterministic composite key generated by
 * generateCartItemId(productId, addonIds) — order-independent.
 */
export interface CartItem {
  id: string; // Composite key: `${productId}::${variantId}::${sortedAddonIds.join(',')}`
  productId: string;
  productName: string;
  /** Selected variant id — required at order time for variant products. */
  variantId: string | null;
  /** Selected size/variant label, null for flat-price products. */
  variantName: string | null;
  productImageUrl: string | null;
  baseUnitPrice: MoneyAmount;
  addonIds: string[]; // Standardized add-on identifier array
  selectedAddOns: CartAddOnSelection[];
  quantity: number; // >= 1
}
